version: "3.3"

services:
  django:
    build:
      context: .
    environment:
      - COMMAND=runserver
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - local.env

  postgres:
    image: postgres:10.1
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
